version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_churn_db
    restart: always
    environment:
      POSTGRES_USER: camilo_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: churn_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: